config/routes.rb
Rails.application.routes.draw do
  
  get 'reports/order_by_hour', defaults: { format: :json }
  
  resources :expenses

  resources :to_dos do
    member do
      get 'mark_done'
    end
  end

  resources :categories, only: [:index, :show] do
    resources :items
  end

  resources :activities, only: [:index]

  resources :store, only: [:edit, :update]
  get 'store/settings'          =>'store#settings'
  get 'store/employees'         =>'store#employees'
  post 'store/new_employee'     =>'store#new_employee'
  patch 'store/edit_employee'   =>'store#edit_employee'
  get 'store/mark_present'      =>'store#mark_present'
  get 'store/mark_absent'       =>'store#mark_absent'

  resources :reports do
  end
  
  resources :orders do
    resources :items
    member do
      get   'order_ready'
      get   'return'
      post  'order_return'
      patch 'cash_out'
      patch 'mark_void'
    end
  end

  resources :items do
    member do
      patch 'add_stock'
      patch 'discontinue'
      patch 'activate'
    end
    collection do
      get 'find_by_code'
      get 'edit_multiple'
      post  'update_multiple'
      patch 'update_multiple'
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

   root 'application#dashboard'

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
  belongs_to :store
  belongs_to :user

  acts_as_sequenced scope: :store_id

  # Automatically use the sequential ID in URLs
  def to_param
    self.sequential_id
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < InheritedResources::Base
  before_action :load_to_do, except: :index
  load_and_authorize_resource
  respond_to :html, :json, :js

  def mark_done
     @to_do.update(is_done: true) 
     redirect_to action: :index
  end

  private

  def to_do_params
    params.require(:to_do).permit(:title, :description, :store_id, :user_id, :due_date, :alert_type)
  end

  def load_to_do
    @to_do = current_user.store.to_dos.where(sequential_id: params[:id]).first
  end

end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/to_dos/_form.html.erb
<%= form_for @to_do, url: to_do_path(@to_do.sequential_id) do |f| %>
  <% if @to_do.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do.errors.count, "error") %> prohibited this to_do from being saved:</h2>

      <ul>
      <% @to_do.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :alert_type %><br>
    <%= f.text_field :alert_type %>
  </div>
  <div class="actions ">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_dos/edit.html.erb
<h1>Editing To Do</h1>

<%= render 'form' %>

<%= link_to 'Show', to_do_path(@to_do.sequential_id) %> |
<%= link_to 'Back', to_dos_path %>

app/views/to_dos/index.html.erb
<div class="row">
  <div class="col s12 m12">
    <div class='card card blue-grey darken-1'>
      <div class="heading hvr-underline-from-center">
        <span class="card-title">ToDo's</span>
        <i class="material-icons right close">keyboard_arrow_up</i>
      </div>
      <div class='card-content'>
        <table class="table custom-list">
          <thead>
            <tr>
              <th>ID #</th>
              <th>Title</th>
              <th>Status</th>
              <th>Description</th>
              <th>Due date</th>
              <th>Alert type</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @to_dos.each do |to_do| %>
              <tr>
                <td><%= link_to "##{to_do.sequential_id}", to_do_path(to_do.sequential_id), class: "btn btn-success btn-xs" %></td>
                <td><%= to_do.title %></td>
                <td><span class="badge badge-edited badge-<%= to_do.is_done %>"><%= to_do.is_done ? 'Yes' : 'No' %></span></td>
                <td><%= to_do.description %></td>
                <td><%= to_do.due_date %></td>
                <td><%= to_do.alert_type %></td>
                <td>
                  <%= link_to 'Edit', edit_to_do_path(to_do.sequential_id) %> | 
                  <%= link_to 'Mark Done', mark_done_to_do_path(to_do.sequential_id) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

  <div class='fixed-action-btn' style="bottom: 45px; right: 24px;">
    <a class='btn-floating btn-large red modal-trigger' href='#new_to_do_modal'>
      <i class='large material-icons'>add</i>
    </a>
  </div>

  <div id="new_to_do_modal" class="modal modal-fixed-footer">
    <%= form_for ToDo.new do |f| %>
      <div class='modal-content'>
        <div class="row">
          <div class="input-field">
            <%= f.text_field :title , autofocus: true %>
            <%= f.label :title %>
          </div>
        </div>
        <div class="row">
          <div class="input-field">
            <%= f.text_area :description %>
            <%= f.label :description %>
          </div>
        </div>
        <div class="row">
          <div class="input-field">
            <%= f.datetime_select :due_date %>
            <%= f.label :due_date %>
          </div>
        </div>
        <div class="row">
          <div class="input-field">
            <%= f.text_field :alert_type %>
            <%= f.label :alert_type %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="input-field">
            <%= f.submit %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  

app/views/to_dos/new.html.erb
<h1>New To Do</h1>

<%= render 'form' %>

<%= link_to 'Back', to_dos_path %>

app/views/to_dos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @to_do.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @to_do.description %>
</p>

<p>
  <strong>Store:</strong>
  <%= @to_do.store_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @to_do.user_id %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @to_do.due_date %>
</p>

<p>
  <strong>Alert type:</strong>
  <%= @to_do.alert_type %>
</p>

<%= link_to 'Edit', edit_to_do_path(@to_do.sequential_id) %> |
<%= link_to 'Back', to_dos_path %>