config/routes.rb
Rails.application.routes.draw do
  
  get 'reports/order_by_hour', defaults: { format: :json }
  
  resources :expenses

  resources :to_dos do
    member do
      get 'mark_done'
    end
  end

  resources :categories, only: [:index, :show] do
    resources :items
  end

  resources :activities, only: [:index]

  resources :store, only: [:edit, :update]
  get 'store/settings'          =>'store#settings'
  get 'store/employees'         =>'store#employees'
  post 'store/new_employee'     =>'store#new_employee'
  patch 'store/edit_employee'   =>'store#edit_employee'
  get 'store/mark_present'      =>'store#mark_present'
  get 'store/mark_absent'       =>'store#mark_absent'

  resources :reports do
  end
  
  resources :orders do
    resources :items
    member do
      get   'order_ready'
      get   'return'
      post  'order_return'
      patch 'cash_out'
      patch 'mark_void'
    end
  end

  resources :items do
    member do
      patch 'add_stock'
      patch 'discontinue'
      patch 'activate'
    end
    collection do
      get 'find_by_code'
      get 'edit_multiple'
      post  'update_multiple'
      patch 'update_multiple'
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

   root 'application#dashboard'

end

app/models/item.rb
class Item < ActiveRecord::Base
  include ActiveModel::Transitions
  include PublicActivity::Model
  tracked except: :update, owner: Proc.new{ |controller, model| controller.current_user }
  tracked store_id: Proc.new { |controller, model| controller.current_user.store_id }

  acts_as_sequenced scope: :store_id

  belongs_to :store
  belongs_to :category
  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :delete_all
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :stock_histories, dependent: :delete_all
  has_many :documents, as: :owner

  validates :name, :sell_price, presence: true
  validates_numericality_of :stock, greater_than_or_equal_to: 0, message: 'Invalid stock'
  validates_uniqueness_of :name, scope: :store_id, message: 'An item with same name exists'

  scope :most_used_items, -> { order('sale_count') }

  state_machine do
    state :available   # first one is initial state
    state :low_stock
    state :out_of_stock#, exit: :exit_out_of_stock
    state :discontinued#, enter: lambda { |item| item.cancel_orders }

    event :available do
      transitions to: :available, from: [:low_stock, :out_of_stock, :discontinued], guard: lambda { |item| item.stock > 0 }
    end
    event :low_stock, success: :notify_low_stock do
      transitions to: :low_stock, from: [:available], guard: lambda { |item| item.stock <= item.stock_threshold }
    end
    event :out_of_stock, success: :notify_out_of_stock do
      transitions to: :out_of_stock, from: [:available, :low_stock], guard: lambda { |item| item.stock == 0 }
    end
    event :discontinued do
      transitions to: :discontinued, from: [:available, :low_stock, :out_of_stock]
    end
  end

  def add_stock quantity, unit_price, total_price
    transaction do
      stock_histories.create(store_id: store_id, stock_quantity: quantity, unit_price: unit_price, total_price: total_price)
      create_activity(key: 'item.add_stock', params: { stock_quantity: quantity })
      update(stock: stock + quantity)
      update_state
    end
  end

  def sale quantity
    stock_histories.create(store_id: store_id, stock_quantity: -1 * quantity, unit_price: sell_price, total_price: sell_price * quantity)
    update_state
  end

  private
  def update_state
    if stock == 0
      self.out_of_stock! unless self.out_of_stock?
    elsif stock > 0 && stock <= stock_threshold
      self.low_stock!    unless self.low_stock?
    elsif stock > stock_threshold
      self.available!    unless self.available?
    end
  end

  def notify_low_stock
    self.create_activity(key: 'item.low_threshold')
    ToDo.create(title: "Low stock", description: "Restock item", store_id: store_id, trackable_type: "Item", trackable_id: id)
  end

  def notify_out_of_stock
    self.create_activity(key: 'item.out_of_stock')
    ToDo.create(title: "Out of stock", description: "Restock item", store_id: store_id, trackable_type: "Item", trackable_id: id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :set_item, only: [:show, :edit, :update, :destroy, :add_stock, :generate_code]
  # load_and_authorize_resource
  load_resource find_by: :sequential_id, except: :update
  load_resource only: :update
  authorize_resource

  respond_to :html, :json, :js

  # require 'barby'
  # require 'barby/barcode/ean_13'
  # require 'barby/outputter/rmagick_outputter'
  # require "rmagick"

  # GET /items
  # GET /items.json
  def index
    @items = @items.where(category: params[:category_id]) if params[:category_id].present? # have to verify this line
    @items = @items.where("name like ?", "%#{params[:query]}%") if params[:query].present? # need this for ajax/json

    @q     = @items.ransack(params[:q])
    @items = @q.result(distinct: true)
    
    @items = @items.page(params[:page])
    respond_with @items
  end


  # GET /items/1
  # GET /items/1.json
  def show
    # if @item.type == 'bakery'
      # outputter = Barby::RmagickOutputter.new(Barby::EAN13.new(@item.code[0..-2]))
      # outputter.xdim = 1
      # outputter.height = 45
      # File.open("public/barcode2.png", 'wb'){|f| f.write outputter.to_png }

      # source = Magick::Image.read("public/barcode2.png").first
      # f = Magick::Image.new(230, 480) { self.density = 300 }
      # (0..6).each_with_index do |i|
      #   f.composite!(source , 115, (106*i)-10, Magick::OverCompositeOp)
      # end

      # f.write("public/barcode.png")
    # end
    @histories = @item.stock_histories
    respond_with @item, location: items_path(@item.sequential_id)
  end

  # GET /items/new
  def new
    respond_with @item
  end

  # GET /items/1/edit
  def edit
    respond_with @item, location: items_path(@item.sequential_id)
  end

  def edit_multiple
    @items = current_user.store.items.where(id: params[:item_ids])
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.store.items.new(item_params)

    if @item.save
      @item.documents.create(image: params[:image])
      flash[:notice] = 'Item was successfully created.'
    end

    # respond_with @item, location: items_path(sequential_id: @item.sequential_id)
    # respond_with @item, location: item_path(@item.sequential_id)
    redirect_to items_path
  end

  def add_stock
    @item.add_stock params[:stock_quantity].to_f, params[:unit_price], params[:total_price]

    # respond_with @item, location: items_path(sequential_id: @item.sequential_id)
    respond_with @item, location: item_path(@item.sequential_id)
  end

  def discontinue
    respond_with @item.discontinued!, location: item_path(@item.sequential_id)
  end

  def activate
    respond_with @item.available!, location: item_path(@item.sequential_id)
  end
  
  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
      @item.documents.create(image: params[:image])
      @item.create_activity key: 'item.update'
      flash[:notice] = 'Item was successfully updated.'
    end

    # respond_with @item, location: items_path(sequential_id: @item.sequential_id)
    respond_with @item, location: item_path(@item.sequential_id)
  end

  def update_multiple
    update_action = { 'add_stock' => 'add_stock', 'set_price' => 'set_price' }[params[:batch_action]]

    if update_action == 'add_stock'
      @items = current_user.store.items.where(id: params[:stock_quantities].keys)
      @items.each do |item|
        item.send(update_action, params[:stock_quantities][item.id.to_s], params[:unit_prices][item.id.to_s], params[:total_prices][item.id.to_s])
      end
    elsif update_action == 'set_price'
      @items = current_user.store.items.where(id: params[:sell_prices].keys)
      @items.each do |item|
        item.update(sell_price: params[:sell_prices][item.id.to_s])
      end
    end

    flash[:notice] = "Updated Items!"
    redirect_to items_path
  end

  # DELETE /items/1
  # DELETE /items/1.json
  # def destroy
  #   @item.destroy
  #   flash[:notice] = 'Item was successfully deleted.'

  #   respond_with @item, location: items_path(@item.sequential_id)
  # end

  def find_by_code
    @items = @items.where(code: params[:code])

    respond_with @items
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_item
    #   @item = Item.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.permit(:image)
      params.require(:item).permit(:name, :buy_price, :sell_price, :stock, :code, :description, :category_id, :stock_threshold)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit_multiple.html.erb
  <%= form_tag update_multiple_items_path do %>
    <%= hidden_field_tag :batch_action, params[:batch_action] %>

    <div class="modal-content">
      <table class="table custom-list">
        <thead>
          <tr>
            <th>Item#</th>
            <th>Name</th>
            <th>Current Price</th>
            <th>Current Stock</th>
            <% if params[:batch_action] == 'set_price' %>
              <th>New Price</th>
            <% else %>
              <th>Add Stock</th>
              <th>Unit Price</th>
              <th>Total Price</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td>#<%= item.sequential_id %></td>
              <td><%= item.name %></td>
              <td><%= item.sell_price %></td>
              <td><%= item.stock %></td>
              <% if params[:batch_action] == 'set_price' %>
                <th><%= number_field_tag "sell_prices[#{item.id}]", 0, required: "required", step: "any", min: 1 %></th>
              <% else %>
                <td>
                  <input type='number' name='stock_quantities[<%= item.id %>]' data-item-id='<%= item.id %>' class='batch_stock' step='any' min='1' value=0 />
                </td>
                <td>
                  <% unit_price = item.stock_histories.present? ? item.stock_histories.last.unit_price : 0 %>
                  <input type="number" name='unit_prices[<%= item.id %>]' data-item-id='<%= item.id %>' class='batch_unit' step="any" min='1' value="<%= unit_price %>" />
                </td>
                <td>
                  <input type="number" name='total_prices[<%= item.id %>]' data-item-id='<%= item.id %>' class='batch_total' step="any" min='1' />
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="modal-footer">
      <%= submit_tag :update, class: 'btn btn-flat right' %>
    </div>

  <% end %>

app/views/items/_form.html.erb
<div>
  <%= form_for @item, html: { multipart: true } do |f| %>
    <div class="modal-content">
      <h1>New Item</h1>
      <div class="row">
        <% if @item.errors.any? %>
          <div id="error_explanation row">
            <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

            <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      </div>

      <div class="input-field">
        <%= f.text_field :name, required: "required" %>
        <%= f.label :name, '', class: 'active' %>
      </div>
 
      <br><br>
      <div class="input-field">
        <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name) %>
        <%= f.label :category_id, 'Category', class: 'active' %>
      </div>

      <br>
      <div class="input-field">
        <%= f.number_field :sell_price, required: "required", step: "any", min: 0 %>
        <%= f.label :sell_price, '', class: 'active' %>
      </div>
    
      <br>
      <div class="input-field" id='item-code-div' >
        <%= f.text_field :code, required: "required" %>
        <%= f.label :code, '', class: 'active' %>
      </div>

      <br>
      <div class="input-field">
        <%= file_field_tag :image %>
      </div>
      <br>
      
      <div class="input-field">
        <%= f.number_field :stock, min: 0 %>
        <%= f.label :stock, '', class: 'active' %>
      </div>
      
      <br>
      <div class="input-field">
        <%= f.number_field :stock_threshold, min: 0 %>
        <%= f.label :stock_threshold, '', class: 'active' %>
      </div>
    
      <br>
      <div class="input-field">
        <%= f.text_area :description, rows: "3", class: 'materialize-textarea' %>
        <%= f.label :description, '', class: 'active' %>
      </div>

    </div>
    <div class="modal-footer">
      <button class="btn waves-effect waves-light btn-flat" type="submit" name="action" >
        Save <i class="material-icons right">send</i>
      </button>
      <a class="btn modal-action modal-close waves-effect waves-red btn-flat">Cancel</a>
    </div>
  <% end %>
</div>

app/views/items/edit.js.erb
$("#new-item-div").html("<%= escape_javascript(render(partial: "form")) %>");
$('select').material_select();
$("#new-item-div").openModal()

app/views/items/edit_multiple.js.erb
$("#new-item-div").html("<%= escape_javascript(render(partial: "edit_multiple")) %>");
$("#new-item-div").openModal();


$('.batch_stock, .batch_unit').on('input', function(){ 
  var id = $(this).data('item-id');

  $(".batch_total[data-item-id='"+ id +"']").val(
      $(".batch_unit[data-item-id='"+ id +"']").val() * $(".batch_stock[data-item-id='"+ id +"']").val()
    );
});

$('.batch_total').on('input', function(){
  var id = $(this).data('item-id');

  $(".batch_unit[data-item-id='"+ id +"']").val(
    $(".batch_total[data-item-id='"+ id +"']").val() / $(".batch_stock[data-item-id='"+ id +"']").val()
  );
});

app/views/items/index.html.erb
<div class="row">
  <div class="col s12">
    <div class='card blue-grey darken-1'>
      <div class="heading hvr-underline-from-center">
        <span class="card-title">Search Item</span>
        <i class="material-icons right close">keyboard_arrow_up</i>
      </div>
      <div class='card-content'>
        <div class="search-from">
          <%= search_form_for @q do |f| %>
            <%= f.label 'Name' %>
            <%= f.search_field :name_cont %>

            <div class="hidden-search-menu">
              <%= f.label :name_or_description_or_stock_cont %>
              <%= f.search_field :name_or_description_or_stock_cont %>
            </div>

            <div>
              <button class="btn waves-effect waves-light" type="submit" name="action">Search
                <i class="material-icons right">send</i>
              </button>
              <i class="right small material-icons expand_more">expand_more</i>
              <i class="right small material-icons expand_less">expand_less</i>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    
    <div class='card blue-grey darken-1 '>
      <div class="heading hvr-underline-from-center">
        <span class="card-title">Items List</span>
        <i class="material-icons right close">keyboard_arrow_up</i>
      </div>
      <div class='card-content'>
        <%= form_tag edit_multiple_items_path, method: :get, remote: true, id: 'items_batch_action_form' do %>
          <%= hidden_field_tag :batch_action %>
          <table class="table custom-list">
            <thead>
              <tr>
                <th><%= sort_link(@q, :sequential_id, 'Item #', default_order: :desc) %></th>
                <th><%= sort_link(@q, :name,          'Name',   default_order: :desc) %></th>
                <th><%= sort_link(@q, :state,         'State',   default_order: :desc) %></th>
                <th><%= sort_link(@q, :price,         'Price',  default_order: :desc) %></th>
                <th><%= sort_link(@q, :stock,         'Stock',  default_order: :desc) %></th>
                <th>
                  <a class="dropdown-button" href="#!" data-activates="dropdown1" data-constrainwidth='false'><i class="material-icons">more_vert</i></a> 
                  <ul id="dropdown1" class="dropdown-content">
                    <li><a class="mark_all" data-checkbox-name='item_ids[]'>Mark All</a></li>
                    <li><a class="mark_none" data-checkbox-name='item_ids[]'>Mark None</a></li>
                    <li class="divider"></li>
                    <li><a class="batch_action_items" data-batch-action='add_stock'>Add Stock</a></li>
                    <li><a class="batch_action_items" data-batch-action='set_price'>Set Price</a></li>
                  </ul>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @items.each_with_index do |item, index| %>
                <tr>
                  <td><%= link_to "##{item.sequential_id}", item_path(item.sequential_id), class: "btn btn-success btn-xs" %></td>
                  <td><%= item.name %></td>
                  <td><span class="badge badge-edited badge-item-<%= item.current_state %>"><%= item.current_state.to_s.humanize %></span></td>
                  <td><%= item.sell_price %></td>
                  <td><%= item.stock %></td>
                  <td>
                    <%= check_box_tag "item_ids[]", item.id, false, id: "item_id_#{item.id}" %>
                    <%= label_tag "item_id_#{item.id}", ' ' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

        <div class="row center-align">
          <%= paginate @items %>
        </div>
      </div>
    </div>

  </div>
</div>

<div id="new-item-div" class="modal modal-fixed-footer modal-large">
</div>


<div class='fixed-action-btn' style="bottom: 45px; right: 24px;">
  <%= link_to new_item_path, remote: true, class: 'btn-floating btn-large red' do %>
    <i class='large material-icons'>add</i>
  <% end %>
</div>
  

app/views/items/new.js.erb
$("#new-item-div").html("<%= escape_javascript(render(partial: "form")) %>");
$('select').material_select();
$("#new-item-div").openModal()

app/views/items/show.html.erb
<div class="row">
  <div class="col s12">

    <div class="card blue-grey darken-1">
      <div class="card-content-full-height card-content white-text">
        <span class="card-title">
          <%= image_tag @item.documents.first.image.url(:thumb) if @item.documents.present? %>
          <%= @item.name %>
          <span class="badge badge-item-<%= @item.current_state %>"><%= @item.current_state.to_s.humanize %></span>
        </span>
        <p><%= @item.description %></p>
        <hr/>
        <table class="hover-feedback">
          <tr>
            <td>Category</td>
            <td><%= @item.category.name %></td>
          </tr>
          <tr>
            <td>Sell Price</td>
            <td><%= @item.sell_price %></td>
          </tr>
          <tr>
            <td>Current Stock</td>
            <td><%= @item.stock %></td>
          </tr>
          <tr>
            <td>Stock Threshold</td>
            <td><%= @item.stock_threshold %></td>
          </tr>
          <tr>
            <td>Code</td>
            <td><%= @item.code %></td>
          </tr>
        </table>         
      </div>
      <div class="card-action">
        <a href="#add_stock_modal" class="waves-effect waves-light btn modal-trigger">Add Stock</a>
        <%= link_to 'Edit', edit_item_path(@item.sequential_id), remote: true, class: "waves-effect waves-light btn" %>
        <% if @item.discontinued? %>
          <%= link_to 'Activate', activate_item_path(@item.sequential_id), data: {:confirm => 'Are you sure?'}, method: :patch, class: "waves-effect waves-light btn" %>
        <% else %>
          <%= link_to 'Discontinue', discontinue_item_path(@item.sequential_id), data: {:confirm => 'Are you sure?'}, method: :patch, class: "waves-effect waves-light btn" %>
        <% end %>
        <a class="waves-effect waves-light btn activator right">History<i class="material-icons right">more_vert</i></a>
      </div>
      <div class="card-reveal grey lighten-2">
        <span class="card-title grey-text text-darken-4">History <i class="material-icons right">close</i></span>
        <ul class="collection">
          <li class="divider"></li>
          <% @histories.each do |history| %>
            <li class="collection-item avatar history-item">
              <% if history.stock_quantity > 0 %>
              <i class="material-icons circle black-text green">file_download</i>
               <span class="title">Added <%= history.stock_quantity  %> <%= @item.name %> in stock</span>
              <% else %>
              <i class="material-icons circle black-text red">file_upload</i>
               <span class="title">Sold <%= -1 * history.stock_quantity  %> <%= @item.name %> from stock</span>
              
              <% end %>
              <p> <%= time_ago_in_words(history.created_at) %> ago</p>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

  </div>
</div>

<div id="new-item-div" class="modal modal-fixed-footer modal-large">
</div>

<div id="add_stock_modal" class="modal modal-fixed-footer">
  <%= form_for @item, url: {action: :add_stock} , method: :patch, class: 'form-horizontal' do %>
    <div class="modal-content">
      <h4>Add Stock</h4>
      <p>Add some stock to your item...</p>
      <div>
        <label>Stock: </label>
        <input type="number" name='stock_quantity' id='stock_quantity' step="any" min="0" />
      </div>
      <div>
        <label>Unit Price: </label>
        <input type="number" name='unit_price' id='unit_price' step="any" min="0" />
      </div>
      <div>
        <label>Total Price: </label>
        <input type="number" name='total_price' id='total_price' step="any" min="0" />
      </div>
    </div>
    <div class="modal-footer">
        <button class='btn waves-effect waves-light btn-flat' type="submit" name="action">Add <i class='material-icons right'>send</i></button>
        <a class='btn modal-action modal-close waves-effect waves-red btn-flat'>Cancel</a>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#stock_quantity, #unit_price').on('input', function(){ 
    $('#total_price').val($('#unit_price').val() * $('#stock_quantity').val());
  });
  $('#total_price').on('input', function(){
    $('#unit_price').val($(this).val() / $('#stock_quantity').val());
  });
</script>